### ISSUE TITLE
feat: PyO3 & Maturin for src/algebra.py

### ISSUE THREAD

**Issue by feltroidprime** [keep-starknet-strange/garaga#110]
Implement Rust bindings for the file [algebra.py](https://github.com/keep-starknet-strange/garaga/blob/rewrite/src/algebra.py) while maintaining same methods and properties. 

Demonstrate performance improvements when running [benchmarks.py](https://github.com/keep-starknet-strange/garaga/blob/rewrite/src/benchmarks.py)

Use https://pyo3.rs/ and PR to _rewrite_ branch. 

Some bench using `py-spy top -- python src/benchmarks.py ` (see [py-spy](https://github.com/benfred/py-spy) ) : 
![image](https://github.com/keep-starknet-strange/garaga/assets/96737978/1a596206-e6c2-496c-bdfd-7994b174f19f)

`make setup` script should be updated and integrated easily.

**Comment by Akashneelesh** [comment]
Heyy @feltroidprime may I try this one. Thanks

**Comment by feltroidprime** [comment]
> Heyy @feltroidprime may I try this one. Thanks

Yes, please explore! Good luck

**Comment by Akashneelesh** [comment]
> > Heyy @feltroidprime may I try this one. Thanks
> 
> Yes, please explore! Good luck !

Thank you serr!
