### ISSUE TITLE
feat: PyO3 & Maturin for poseidon_transcript.py

### ISSUE THREAD

**Issue by feltroidprime** [keep-starknet-strange/garaga#111]
Implement Rust bindings for the file [poseidon_transcript.py](https://github.com/keep-starknet-strange/garaga/blob/rewrite/src/poseidon_transcript.py) while maintaining same methods and properties. 

Demonstrate performance improvements when running [benchmarks.py](https://github.com/keep-starknet-strange/garaga/blob/rewrite/src/benchmarks.py)

Use https://pyo3.rs/ and PR to _rewrite_ branch.

**Comment by StarkFishinator** [comment]
Hi, I would like to try this one :)

**Comment by feltroidprime** [comment]
@all-contributors please add @StarkFishinator
