### ISSUE TITLE
feat: Rust implementation and PyO3 bindings of final exponentiation witness.  

### ISSUE THREAD

**Issue by feltroidprime** [keep-starknet-strange/garaga#133]
# Feature Request

**Describe the Feature Request**

We want to have a Rust implementation of this function that can be importable with PyO3 binding and maturin https://github.com/keep-starknet-strange/garaga/blob/84c8ccbd3e7e81e90f755195ff564164a6ff6fca/hydra/hints/multi_miller_witness.py#L14-L25

Implementation involves basic integer function (gcd, modular inverse), as well as exponentiation in the target group of both pairing curves (Fq12). 

Recommended crates to use Fq12 are 
https://docs.rs/ark-bn254/latest/ark_bn254/
https://docs.rs/ark-bls12-381/latest/ark_bls12_381/

**Describe Preferred Solution**

A PyO3 binding already exists in Garaga for hades_permutation https://github.com/keep-starknet-strange/garaga/tree/contracts/tools/hades_binding
Using the following setup https://github.com/keep-starknet-strange/garaga/blob/84c8ccbd3e7e81e90f755195ff564164a6ff6fca/tools/make/setup.sh#L58-L61 the binding was made available to https://github.com/keep-starknet-strange/garaga/blob/84c8ccbd3e7e81e90f755195ff564164a6ff6fca/hydra/poseidon_transcript.py#L11-L21

Ultimately we want to have a single crate in garaga, named `garaga-rs`, that will hold rust bindings under one subfolder, ie using it from python will look like:
```
import garaga_rs
garaga_rs.hades_permutation
garaga_rs.get_final_exp_witiness
``` 

The function should take a curve identifier (integer) to map to the correct `Fq12` instance (`0` for BN254, `1` for BLS12-381, see https://github.com/keep-starknet-strange/garaga/blob/84c8ccbd3e7e81e90f755195ff564164a6ff6fca/hydra/definitions.py#L34-L39), and a list (or tuple) of 12 integers to represent the miller loop output `f`. 
The python wrapper that will call the binding can convert the python `E12` type to a list of 12 integers ready to instantiate a Rust Fq12 object using https://github.com/keep-starknet-strange/garaga/blob/84c8ccbd3e7e81e90f755195ff564164a6ff6fca/hydra/hints/tower_backup.py#L334-L348

On the way back from Rust, to create a E12 object from the 12 integers returned by the rust binding, E12 can be instantiated with a list of PyFelt. 

**Related Code**

A rust implementation of the bn254 case is available in https://github.com/geometers/pairing-witness/
However, it is recommend to follow the pure python implementations available in Garaga as reference. 

**Additional Context**

The goal of this function is to provide extra data to verify a product of pairing is equal to 1 in the target group. 
Instead of verifying `final_exponentiation(miller(P_1, Q_1) * ... * miller(P_n, Q_n)) == 1`, instead, provide a lambda-th root `c` and a scalaing factor `w` , such that `miller(P_1, Q_1) * ... * miller(P_n, Q_n)  * w == c^lambda,` which is much more efficient thanks to the nature of lambda. 

Additional details are available in https://eprint.iacr.org/2024/640.pdf section 4.

**Comment by raugfer** [comment]
BLS implementation got faster / simpler thanks to a merge from the paper author yesterday: https://github.com/keep-starknet-strange/garaga/blob/cbc444e305fc1d0b4d57d13eff030ff602462d4c/hydra/hints/bls.py#L58-L66 as simple as this
