### ISSUE TITLE
dev: Include risc0 generator logic in the `garaga gen` command

### ISSUE THREAD

**Issue by stefanMadzharov** [keep-starknet-strange/garaga#215]
In the moment there is no way to easily generate the risc0 verifier contract through the CLI although the functionality is in `generator_risc0.py`. When `garaga gen --system groth16 --vk hydra/garaga/starknet/groth16_contract_generator/examples/vk_risc0.json` is called the output is the default groth16 verifier contract and not the specific risc0 one. A logic which decides which type of verifier contract should be generated should be added to `gen.py`

**Comment by feltroidprime** [comment]
Since the vk is constant, we don't need to allow generation for it in the CLI. 

It's better to maintain one contract for everyone and publish it on mainnet and put it in the docs
