### ISSUE TITLE
feat: CI(release) Verify ECIP ops class hash is declared on Mainnet & Sepolia

### ISSUE THREAD

**Issue by feltroidprime** [keep-starknet-strange/garaga#240]
The [pip package release CI](https://github.com/keep-starknet-strange/garaga/blob/0981867fb03530f7e14cb1dda7a9e5d0eb9da318/.github/workflows/maturin.yml#L157-L171) should assert the ECIP OPS class hash hardcoded in https://github.com/keep-starknet-strange/garaga/blob/0981867fb03530f7e14cb1dda7a9e5d0eb9da318/hydra/garaga/starknet/groth16_contract_generator/generator.py#L11 is _declared_  both on Starknet Sepolia and Starknet Mainnet before publishing.

Notes : 
- the class hash value should be parsed from the python code ([the devnet e2e CI test is already asserting](https://github.com/keep-starknet-strange/garaga/blob/0981867fb03530f7e14cb1dda7a9e5d0eb9da318/tests/contracts_e2e/e2e_test.py#L91-L93) this value is equal to the class hash of the [commited contract](https://github.com/keep-starknet-strange/garaga/tree/main/src/contracts/universal_ecip))
- the contract only needs to be declared, not necessarily deployed

**Comment by bruhhgnik** [comment]
can i take up on this issue? @feltroidprime

**Comment by feltroidprime** [comment]
> can i take up on this issue? @feltroidprime

Yes.

**Comment by bruhhgnik** [comment]
@feltroidprime thanks a lot!
