### ISSUE TITLE
Add needed gnark tower operations to go cli

### ISSUE THREAD

**Issue by tekkac** [keep-starknet-strange/garaga#25]
# Feature Request

**Describe the Feature Request**

Update the go CLI implementation with the needed e12 and  e6 operations

**Describe Preferred Solution**

- Add an argument to the command to be able to pick the field to do the operations from (e2, e6 and e12).
Currently, only e2 is available.
- Modify main.go CLI to be able to call operation using a specific command and parse the specific input.

**Describe Alternatives**

**Related Code**
old:
`./main op 1 2 3 4` 
needed
`./main field op [x as a list of fp limbs]  [y as a list of fp limbs]̀`

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [X] Yes
- [ ] No

**Comment by sdgalvan** [comment]
Hi! Can I take this? Not an expert on Go but can try

**Comment by feltroidprime** [comment]
closed with #26 and commits 8904b806bcbab143743a48d8a9701e1ad3f6ffe9 and 88234cd43ce53f7fdacd2402a4661658fe86bb74
