### ISSUE TITLE
feat: Update PyO3 to 0.23.3

### ISSUE THREAD

**Issue by feltroidprime** [keep-starknet-strange/garaga#273]
Update dependencies of PyO3 in https://github.com/keep-starknet-strange/garaga/blob/main/tools/garaga_rs/Cargo.toml to version 0.23.3 and update code so that `cargo build` outputs no deprecation warnings. 

See https://pyo3.rs/v0.23.0/migration.html

**Comment by sigmadawg** [comment]
i want to solve this issue, can i take this up?

**Comment by feltroidprime** [comment]
yes
