### ISSUE TITLE
bug: fq_eq_zero and fq_eq_one needs to be fixed in BLS12-381 fq.cairo

### ISSUE THREAD

**Issue by onurinanc** [keep-starknet-strange/garaga#74]
The checks are done for the BigInt3 not for the BigInt4, x.d3 == 0 needs to be added to both functions

**Comment by onurinanc** [comment]
https://github.com/keep-starknet-strange/garaga/blob/main/src/bls12_381/fq.cairo#L28

**Comment by feltroidprime** [comment]
Thank you for noticing that point. Will fix soon.
